baseURL = "/"
languageCode = "en-us"
DefaultContentLanguage = "en"

title = "OPRAmachine Documentation"
theme = "docdock"
themesdir = "././themes"

[params]
editURL = "https://github.com/gavinrozzi/opramachine-docs/edit/master/content/"
showVisitedLinks = true # default is false
themeStyle = "original" # "original" or "flex" # default "original"
themeVariant = "" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"
disableHomeIcon = false # default is false
disableSearch = false # default is false
disableNavChevron = false # set true to hide next/prev chevron, default is false
DateForm = "2.1.2006"

[outputs]
home = [ "HTML", "RSS", "JSON"]


[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "File new OPRA request"
identifier = "ds"
url = "https://opramachine.com/select_authority"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-camera'></i> Request Templates"
url = "/opra-request-templates"
weight = 11

[[menu.shortcuts]]
name = "<i class='fa fa-bookmark'></i> Facebook Group"
identifier = "hugodoc"
url = "https://www.facebook.com/groups/njopra/"
weight = 20

[[menu.shortcuts]]
name = "<i class='fa fa-bullhorn'></i> Credits"
url = "/credits"
weight = 30
