baseURL = "/"
languageCode = "en-us"
DefaultContentLanguage = "en"

title = "OPRAmachine Documentation"
theme = "hugo-theme-learn"
themesdir = "././themes"

[params]
editURL = "https://github.com/gavinrozzi/opramachine-docs/edit/master/content/"
showVisitedLinks = true # default is false
themeVariant = "blue" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"
disableHomeIcon = false # default is false
disableSearch = false # default is false
disableNavChevron = false # set true to hide next/prev chevron, default is false

[outputs]
home = [ "HTML", "RSS", "JSON"]


[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "File new OPRA request"
identifier = "ds"
url = "https://opramachine.com/select_authority"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-bookmark'></i> NJ OPRA Facebook Group"
identifier = "hugodoc"
url = "https://www.facebook.com/groups/njopra/"
weight = 20
